### ISSUE TITLE
warning in draw-glyphs may cause a recursive lock attempt

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#1077]
This problem has been noticed by Greg Bennett.

When we start the clim-listener without slime and use it to start another application, then warnings are printed in said clim-listener. If such warning is issued from medium-draw-text* (which grabs a glyph-drawing global lock), then clim-listener calls medium-draw-text* to print such warning and we hit a deadlock. Steps to reproduce:

1. start clim-listener from the console (i.e not via slime)
2. start clim-demo:demodemo from inside the listener
3. run the coordinate swizzling demo

- Expected: works
- Observed: an overly long backtrace

**Comment by dkochmanski** [comment]
the obvious solution is to remove the warning about drawing outside of the mirror, there are two more improvements:
- clip the drawing area properly (and maybe rearrange how invoke-display-function is called to first record, then reply)
- think about whether we could avoid locking in the glyph rendering code

**Comment by scymtym** [comment]
Somewhat related to #888l.

**Comment by john-a-carroll** [comment]
Also related to #793 and #927. In my application I tried the proposed solution `(clim:with-output-recording-options (pane :record t :draw nil) ...)` but still the bad behaviour occurred since redisplay could happen outside the control of my code. So I decided to patch `draw-glyphs` to remove the warning. It would be great to have a 100% reliable solution to this issue.
