### ISSUE TITLE
command-table menu and keystroke accelerators

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#1147]
Working on issue #1144 I noticed that the command-table menu and keystrokes implementation in McCLIM doesn't follow all the
specification (chapter 27). There are also some problems in the specification itself. 

# Where McCLIM don't follow the specification
1. For the Spec (27.2) in the command table there is a table that associates keyboard gesture names to menu items, in McCLIM the keystroke are stored directly in menu items (class `%menu-item` in McCLIM).

2. For spec (27.3) menu items are stored as a list of the form `(type value . options)`, in McCLIM instead they are stored as instance of class `%menu-item`.
  
3. For spec (27.4) `lookup-keystroke-command-item` must return only the enabled command, in McCLIM this is not the case. Solving this can solve issue #1144 (solved with PR #1146).
   
4. The function `map-over-command-table-keystrokes`  in McCLIM accept also the key `inherited` that isn't in the spec (27.4).

5. For the spec when the `type` of a menu-item is `:menu` the value must be a command table, McCLIM accept also a list like `("Submenu" :menu (("Comm 1" :command  com-a-command) ("Comm 2" :command com-another-command)))`. I like this extension.

6. In the spec there are two menu-item object, one for menu in the command table (spec 27.3) and one for menus of facilities (spec 25). For McCLIM they are the same things (view comment in processor.lisp) before the definition of menu-item presentation-type.

7. How the command-table inherit menu and keystrokes. But this is one of the main problems of the spec: more on this later.

# Problems with CLIM specification
1. In `make-command-table` with `:inherit-menu` you inherit the menu and/or the accelerators from all the command-table ancestor. It is not possible to inherit menu only from some ancestor command tables. A syntax like `(make-command-table 'new-table :inherit-from '(table-1 (table-2 :menu) (table-3 :keystrokes) (table-4 t)))` will be better.

2. `lookup-keystroke-item` is different from `find-keystroke-item` because it follow the sub-menu chains. But which sub-menu chains?  The chains in the keystrokes table or the chain in the menus  table. I opt for the first.

3. `lookup-keystroke-command-item` has a name similar to  `lookup-keystroke-item` so it is natural thinking that its behaviour
  is to follow the submenu, but in the spec it is written that it is  like `find-keystroke-item`. In the Franz manual instead it is  written that it is like `lookup-keystroke-item`. 

4. What does it mean inherit menu and keystrokes exactly? When the   comand-table is created (by `make-command-table` or
   `define-command-table`) there is the `:inherit-menu` keyword,   but in the spec its written that menu and keystrokes aren't   inherited. The CLIM lispkworks manual drastically solve the   situations, the `:inherit-menu` key is removed form   `define-command-table` and `make-command-table`. CLIM-TOS instead   copy the menu entry from the ancestor table to the new-table when   this is created. In this way the child table have the same entries of   the ancestor but not "dynamically" inherit them. I opt for this   solution.

6. With submenus in the keystrokes table will be possible (changing   `read-command-using-keystroke`) to have "emacs like" keystrokes   (C-x C-f). As an extension if a submenu have as keystroke a special   value like (nil or :top-level) the keystrokes of the   submenu table could be treated as top-level keystrokes.

**Comment by dkochmanski** [comment]
I will take a look in more detail at your remarks when I'm done with double buffering (I'm working on it now). I've recently changed substantially how menu items and keystrokes are stored in the command table (so you may check the recent git history). Also you may want to check the tests I've written to ensure the behavior.

1)  It is also not specified, how the keystroke is associated - the accelerator and menu tables may be one and the same thing. In fact this design was inspired with how CLIM-TOS does that - much clearer design.
2) %menu-item was present before - it doesn't seem to be a big deal given that the object should be always accessed with the accessor.
3) makes sense, it was most likely an omission on my side.
4) yes, this was discussed during the peer review, I've decided that this change is backward-compatible and provides a better interface
5) old extension - was broken, I've fixed it recently
6) couldn't it be that the presentation type is independently specified in two places?

-------------

Problems with CLIM specification -- did you check with the spec version after this commit?

3cbb1646 Documentation: update the specification of menu items and keystrokes

1. I don't like this idea,  it makes the code less comprehensive, if you really want to achieve such effect, you could consider an alternative:

```
(make-command-table 'new-table
  :inherit-from (list (make-command-table nil :inherit-from table-1)
                             (make-command-table nil :inherit-from table-2 :inherit-menu :menu)
                             (make-command-table nil :inherit-from table-3 :inherit-menu :keystrokes)
                             (make-command-table nil :inherit-from table-4 :inherit-menu t))
  :inherit-menu t)
```

2. this function is interesting because first, it needs to traverse inherited items (to see if any of them has an associated keystroke, just like find-keystroke-item), and then it does the same for each sub-menu (which, as we know, is another command table that is not necessarily an ancestor of our table). That much seems clear to me for this function. I've imposed one more constraint (and added it to the specification), that the submenu is not descended into if it has a keystroke of its own. This is to allow keystroke combinations (i.e open a submenu with its combination, and then keystrokes of its own are available) -- this is not implemented yet though.
 
3. I agree with that observation. fwiw we implement it like franz manual says - we need o update our spec.

4. We have already implemented a dynamic behavior (and added it to the specification in our source code)
- inherit-menu :keystrokes means, that we inherit only keystrokes from the ancestor
- inherit-menu :menu means, that we inherit only menu items from the ancestor
- inherit-menu t means two of the above
- inherit-menu nil means that we inherit none
i.e when we call find-menu-item, we call map-over-command-table-menu with the :inherited keyword (internal function).

5. yes, I have stashed something similar (and more). I've even demoed it somewhere (maybe linked on #clim irc channel?). We need that functionality for input editors.

**Comment by admich** [comment]
I learned now that the specification in McCLIM repo are updated, I always read the version linked in McCLIM home page. Is it this version published on the web? Is it possible compile this version in html and integrate it with hyperclim.el (I cheked the Makefile but seems that it compille the spec only in pdf)?

Seems to me that you already answered to almost all my question, so I close the issue.
