### ISSUE TITLE
Menus flash and some items can't be selected if user clicks without releasing

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#1171]
```
(in-package :clim-user)

(define-application-frame menutest ()
    ()
  (:pane :application))

(define-menutest-command com-item ()
  (format *trace-output* "~&com-item~%"))

(define-command-table file-command-table
                      :menu (("File 1" :command com-item)
                             ("File 2" :command com-item)
                             ("File 3" :command com-item)
                             ("File 4" :command com-item)))

(define-command-table edit-command-table
                      :menu (("Edit 1" :command com-item)
                             ("Edit 2" :command com-item)
                             ("Edit 3" :command com-item)
                             ("Edit 4" :command com-item)))

(define-command-table windows-command-table
                      :menu (("Windows 1" :command com-item)
                             ("Windows 2" :command com-item)
                             ("Windows 3" :command com-item)
                             ("Windows 4" :command com-item)))

(define-command-table menutest
                      :menu (("File" :menu file-command-table)
                             ("Edit" :menu edit-command-table)
                             ("Windows" :menu windows-command-table)))

(run-frame-top-level (make-application-frame 'menutest))
```

The menus behave very nicely when they are opened with a mouse button click and immediate release. However, if the user clicks without releasing and then drags across the menu bar, the menus flash disconcertingly and after a while it becomes impossible to select items from some of them because the wrong menu gets displayed.

**Comment by dkochmanski** [comment]
The issue comes from the fact, that:

1) we grab a sheet in tracking-pointer with multiple-window (port-grabbed-sheet is t)
2) the sheet is pressed so it receives event copies

I think that the correct solution will be to not treat a pressed sheet especially (i.e gadgets that want it to be treated specially will need to pointer-grab the sheet), but this change will be quite impactful:
- it changes behavior of distribute-event
- it requires identifying all gadgets that depend on the pointer being grabbed
- extra care needs to be put for sheets that doesn't have a direct mirror

**Comment by dkochmanski** [comment]
when I simply comment out distribution of the event copy in the method distribute-event then menu bar doesn't flicker and everything works as expected (but for example sliders doesn't work as before).

**Comment by dkochmanski** [comment]
I've pushed a conservative change that addresses this issue. It may be superseded by #1177 in the future.
