### ISSUE TITLE
Does McCLIM support Common-lisp?

### ISSUE THREAD

**Issue by codehangen** [McCLIM/McCLIM#1314]
Hi all! 

> "McCLIM works with Allegro CL, Clozure CL, CLISP, CMUCL, Embeddable CL, the Scieneer CL Common-lisp, SBCL and the LispWorks implementations. Right now the only backend supported by McCLIM is CLX, which ties it to the Xserver on the host system. Any platform capable of running Xserver may run McCLIM applications."

I've read that McCLIM supports these implementations: ```Allegro CL```, ```Clozure CL```, ```CLISP```, ```CMUCL```, ```Embeddable CL```, ```the Scieneer CL Common-lisp```, ```SBCL```, and ```LispWorks``` implementations. 

My doubt would be possible to use MCCLIM in Mezzano-os, if it would be that there would be McCLIM compatibility for Mezzano-os, Mezzano-os is written in common-lisp. In that sense, is there support?

If anyone can clarify or confirm this information, I would be happy for the answer.

**Comment by dkochmanski** [comment]
Hey @codehangen; there are a few things that needs to be unwrapped:

- McCLIM aims to be written in portable common lisp (+ some portability libraries, so some porting may be needed), in this sense it does support Common Lisp because it is a Common Lisp program meant to be compiled and run by the Common Lisp implementation - it compiles also on Mezzano

- Display Server (i.e putting a window on a screen and reading events that the operating system generates for it) is abstracted away by a "backend", so it is possible in theory to use McCLIM with different display servers (i.e X11, Mezzano native windowing, GTK etc)

So your question is whether McCLIM ships a backend that handles Mezzano OS. "Yes" and "No" is probably the right answer.

@fittestbits wrote an off-tree backend for Mezzano and that version of McCLIM is shipped with one of its demos (Demo4 I think), using the software renderer. You may find this fork here: https://github.com/fittestbits/McCLIM. This backend has bitrotten compared to the upstream McCLIM version and does not work with it.

I've recently made an attempt to resurrect the backend while working on SDL2 backend and some alpha-quality files that load and are able to start a window (not much testing has been done though) is in the branch `backend-sdl2` (this is a wip branch, so there are frequent rebases) in the directory Backends/Mezzano.

As for the "no" part - no, upstream McCLIM does not work currently on Mezzano. I hope that this answers your question.
