### ISSUE TITLE
Error in display TEXT-FIELD and TEXT-EDITOR gadget

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#1332]
When I type in `text-field` and `text-editor` gadget I don't see the typed text but all is white. It is like the background color is drawn after the text. The same in Climacs.

![Peek 22-02-2023 18-25](https://user-images.githubusercontent.com/20789240/220708907-d774c150-510b-48c0-884b-e2bd0ca16817.gif)

The problem is from commit: 7528c7d5

**Comment by dkochmanski** [comment]
thanks for the report. I'm aware of this regression. It is due to how drei behaves I think.

I'm working on a replacement, please see the input-editor branch (just shove away the last commit which is in-transition change).

**Comment by dkochmanski** [comment]
I've considered initially reverting the commit but then I've decided to bite the bullet and finish the drei replacement. too many times I had to revert perfectly good changes  because drei mixes redisplay with repaint or makes other dumb assumption (like that all sheets have a medium bound at all times).

**Comment by admich** [comment]
ok, thanks.

**Comment by admich** [comment]
Now TEXT-FIELD and TEXT-EDITOR work, but Climacs still no. I imagine because it use DREI while the gadgets use the new input-editor.

Is it DREI (and therefore Climacs) obsolete and it will be removed from McCLIM? Or is it possible to fix DREI?

**Comment by dkochmanski** [comment]
I don't know whether it is possible to fix drei (and climacs) - in fact I think that the problem is with ESA. I'm working towards removing drei as a dependency of mcclim - it made me revert changes one time too many.

I'm not planning to remove it from mcclim per se, but I'm not planning to maintain it neither. So if someone steps in and makes it work it will be for the better.
