### ISSUE TITLE
dragging-output doesn't work if the pane is not the first one.

### ISSUE THREAD

**Issue by stassats** [McCLIM/McCLIM#398]
Taking the dragndrop example and putting INTERACTOR before SCRATCHPAD makes the mouse position being incorrectly tracked:
https://gfycat.com/ShimmeringDismalCopperhead

**Comment by josrr** [comment]
I also see the issue without the change in the panels; only is necessary to move the pointer outside the pane or use the scroll bar:
https://gfycat.com/GlamorousLegalHoopoe

**Comment by nsrahmad** [comment]
Example uses `t` and `*standard-output*` to output drawings. According to [spec](http://bauhh.dyndns.org:8000/clim-spec/28-3.html#_1496), `*standard-output*` will be bound to the first named pane of the application frame. When we have multiple panes, It is preferable to output drawings to the specific panes.

For example, If we want to output "Hello" to `scratchpad` pane &ndash;instead of doing `(format t "Hello")`&ndash; it is preferable to do:
```common-lisp
(let ((pane (get-frame-pane *application-frame* 'scratchpad)))
  (format pane "Hello"))
``` 

Tracking pointer manually is error-prone and not recommended (example dates back from 2004, so maybe mcclim had missing-pieces back then). We can easily get mouse pointer position with `clim:stream-pointer-position`; Drawing the circle with this point as center simplifies the example. 

`dragging-output` returns final `x` and `y` positions of the pointer, so using those values for drawing dropped circle makes sure that it is drawn wherever the dragging-circle visually appears on the screen.

You can test again with updated `dragndrop` example. It shouldn't depend on the order of the pane, and handle drag-and-drop just fine with scrollbars. (There is a bug (#370) that prevents adding a new circle correctly when pane is scrolled).

**Comment by stassats** [comment]
It's still bogus with
```
(define-dragndrop-command (com-clone-circle)
    ((original circle)
     (start-x real)
     (start-y real))
  ;; Track the pointer offset from the center of the original object
  (let ((x-offset (- (x original) start-x))
        (y-offset (- (y original) start-y))
        (scratchpad (find-pane-named *application-frame* 'scratchpad)))
    (multiple-value-bind (final-x final-y)
        (dragging-output (scratchpad :finish-on-release t)
          (draw-circle* scratchpad (x original) (y original)
                        (radius original)
                        :filled nil ))
      (com-add-circle (+ final-x x-offset)
                      (+ final-y y-offset)
                      (radius original)))))
```

**Comment by nsrahmad** [comment]
@stassats Instead of `find-pane-named` (which returns any type of pane), it is preferred to use `get-frame-pane` (which makes sure it's stream pane). You also need to update `com-add-circle` with:
```common-lisp
(define-dragndrop-command (com-add-circle)
    ((x real :prompt "x")
     (y real :prompt "y")
     (radius real :prompt "radius"))
  (let ((scratchpad (get-frame-pane *application-frame* 'scratchpad)))
    (with-output-as-presentation
	(scratchpad (make-instance 'circle :x x :y y :radius radius) 'circle)
      (draw-circle* scratchpad x y radius ))))
```
But Thats not the only thing wrong with the example. I am posting new (not yet merged) `dragndrop.lisp` example below:
```common-lisp
(in-package :clim-demo)

(define-application-frame dragndrop ()
  ()
  (:pointer-documentation t)
  (:panes
   (interactor :interactor)
   (scratchpad :application :display-time nil :height 600 :scroll-bars nil))
  (:layouts
   (default
    (vertically ()
      (scrolling (:height 300)
	scratchpad)
      interactor))))

(defclass circle ()
  ((center :accessor center :initarg :center)
   (radius :accessor radius :initarg :radius))
  (:default-initargs :radius 50 :center nil))

(defun get-pointer-position (pane)
  (multiple-value-bind (x y) (stream-pointer-position pane)
    (make-point x y)))

(define-dragndrop-command (com-add-circle)
    ((center point :prompt "point")
     (radius real :prompt "radius"))
  (let ((pane (get-frame-pane *application-frame* 'scratchpad)))
    (with-output-as-presentation
	(pane (make-instance 'circle :center center
				     :radius radius)
	      'circle)
      (draw-circle pane center radius))))

(define-dragndrop-command (com-quit-dragndrop :name "Quit")
    ()
  (frame-exit *application-frame*))

(define-presentation-to-command-translator translator-draw-circle
    (blank-area com-add-circle dragndrop
                :documentation "Add a circle")
    (object)
  (list (get-pointer-position
	    (get-frame-pane *application-frame* 'scratchpad))
	50))

(define-dragndrop-command (com-clone-circle)
    ((original circle))
  (let ((pane (get-frame-pane *application-frame* 'scratchpad)))
    (multiple-value-bind (x y)
	(dragging-output (pane :finish-on-release t)
	  (draw-circle pane (get-pointer-position pane)
		       (radius original)
		       :filled nil))
      (com-add-circle (make-point x y) (radius original)))))

(define-presentation-to-command-translator translator-clone-circle
    (circle com-clone-circle dragndrop)
    (object)
  (list object))

(defun drag-circles ()
  (run-frame-top-level (make-application-frame 'dragndrop)))
```

**Comment by stassats** [comment]
Your code is still broken with
```
(:layouts
   (default
    (vertically ()
      interactor
      scratchpad)))
```

**Comment by nsrahmad** [comment]
Try removing the `:scrollbars nil` option from `scratchpad` definition. This seems to be another bug in McClim. Without scrollbars, `pointer-sheet` of the pointer somehow ends up `NIL`, which means `stream-pointer-position` currently only works with `scroller-panes`.

**Comment by stassats** [comment]
That works better. But it's still adding circles whenever the pointer is clicked in the interactor pane.

**Comment by stassats** [comment]
And using your code but changing to
```
(define-application-frame dragndrop ()
  ()
  (:pointer-documentation t)
  (:panes
   (interactor :interactor)
   (x :application
           :scroll-bars nil
           :max-height 20
           :min-height 20)
   (scratchpad :application :display-time nil :height 600 :scroll-bars nil))
  (:layouts
   (default
    (vertically ()
      x
      scratchpad
      interactor))))
```

nothing works again.

**Comment by stassats** [comment]
This reminds of twiddling with CSS to get things to work on IE6...

**Comment by dkochmanski** [comment]
nb: dragging behaves differently when we take dnd translator demo.

**Comment by dkochmanski** [comment]
Please see if problems still occur after a recent rewrite of tracking-pointer and drag-output-record.

**Comment by stassats** [comment]
I don't remember what was the original code that prompted this, but things still seem wonky if the pointer leaves the pane.

**Comment by nsrahmad** [comment]
No longer valid.
