### ISSUE TITLE
detailed description on how to get clim to work on windows

### ISSUE THREAD

**Issue by copypasteearth** [McCLIM/McCLIM#542]
hello,
I can get mcclim to work on Linux but I cannot get it to work on windows, I read the clx backend page but I cannot understand how to get it to work. if you could put more detail into it like how to run sbcl with DISPLAY=localhost:0 to avoid fallback and run startxwin -- -listen tcp  startxwin not a recognized command. just a little more detail thank you

**Comment by copypasteearth** [comment]
or is there a solution to make windows gui executable, that's what im trying to do

**Comment by nsrahmad** [comment]
I assume you have SBCL and Quicklisp setup (if not see [Portacle](https://portacle.github.io/)), Also that method on wiki is complex. There is a simpler solution:
1) CLX backend requires running X server on windows. We will use Xming because it doesn't require any extra setup.
2) Get Xming installer from [here](https://sourceforge.net/projects/xming/)(2.2 MB).
3) Install it with default settings. Once installed, Run it. It opens a Wizard, just accept the defaults. (once running it won't open any windows but you can still see it running in the tray).
4) Get DejaVu fonts from [here](https://sourceforge.net/projects/dejavu/). Extract the archive find the ttf fonts inside. Select all -> Right Click -> Install.
5) Now you can load McCLIM demos in SBCL by running `(ql:quickload "clim-examples")`. Run the demos with `(clim-demo:demodemo)`. 

For building executables, check out [Common Lisp Cookbook](http://lispcookbook.github.io/cl-cookbook/scripting.html). Note that each time before running the executable, you have to make sure Xming is also running.

**Comment by copypasteearth** [comment]
is there any way to make a windows executable that will run without having xming running

**Comment by nsrahmad** [comment]
Currently, Xming is needed, there's no way around it. You can bundle the Xming with your executable. Then it is possible to [start](http://lispcookbook.github.io/cl-cookbook/os.html#running-external-programs) the xming from lisp executable before calling the main clim function.
There is also a [SDL2 backend](https://github.com/McCLIM/McCLIM/wiki/CLDK-Backend), which will need sdl2.dll. Its still a WIP and might not work properly.

**Comment by nsrahmad** [comment]
I've updated wiki about using Xming to run McCLIM on windows.
