### ISSUE TITLE
define-presentation-to-command-translator tester function fires even if gesture doesn't match

### ISSUE THREAD

**Issue by slyrus** [McCLIM/McCLIM#559]
In my define-presentation-to-command-translator definition, e.g.:

```
(define-gesture-name show-task-info-gesture :pointer-button (:left))

(define-presentation-to-command-translator show-task-info-translator
    (task com-show-task-info gantlet-app
          :gesture show-task-info-gesture
          :menu nil
          :tester ((object presentation event context-type)
                   (declare (ignore presentation event context-type))
                   (print context-type *debug-io*)
                   (taskp object))
          :documentation "Show info for this task.")
    (object)
  (list object))
```

The :tester function is called even if the gesture doesn't match. In this case the :tester function is called even on a mouse-over event, not just a button-press. This seems wrong to me.

**Comment by nsrahmad** [comment]
If you have a `pointer-documentation` pane, On mouse-over you can see in the `pointer-documentation` pane what command will run with left, right and middle mouse buttons. Can you guess how it works?

1) Tester determines if a translator applies or not **before** you actually run the translator body. It tester is applicable, it highlights the presentation otherwise it does not.
2) A gesture is only applicable when the presentation is highlighted i.e when the tester has already ran and determined it was applicable.
3) 1 has to happen before 2.

It will be a usability nightmare, If you have to click to find out it a translator is applicable.

**Comment by slyrus** [comment]
Ok, thanks for the explanation. Closing.
