### ISSUE TITLE
Displaying large amounts of text gives multiple warnings about rendering string outside the mirror

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#793]
Attempting to display large amounts of text results in multiple messages

`WARNING: Trying to render string outside the mirror`

To reproduce, run the example code in #630 "glitches during long display". If the loop upper limit in the function `demo` is changed to 1791 or less then there are no problems.

This is with mcclim-20190521-git, clx-20190521-git, SBCL 1.5.0, macOS 10.12.6, XQuartz 2.7.11. The warning is signalled somewhere inside `mcclim-font:draw-glyphs`.

**Comment by john-a-carroll** [comment]
I should have added: this is a regression, since there is no problem with mcclim-20181210-git, clx-20181210-git

**Comment by dkochmanski** [comment]
I've failed to find the actual bug report, but this warning was introduced to make the issue more apparent. Here's the gist of it:

when we draw-text* (i.e do not replay output records), then coordinates may be arbitrary and in the worst case they go beyond the maximum mirror size (32k on X11). Since it is an initial display swizzling is not active yet, so some X11 servers signal an error. Now we catch the overboard position and instead of calling the draw function we just signal a warning.

The issue is valid, but warning is only a recently added canary, not the problem itself.

**Comment by dkochmanski** [comment]
Quick check in git-blame shows commit 1363dbd98d9006377e4bdc399e53f1b1c416bb86 and issue #750. So this wasn't directly addressing wrong coordinates which I have described above, though my memory tells me that what I've described is correct.

**Comment by john-a-carroll** [comment]
Aha, thanks for the explanation. Wrapping the output loop in

`(clim:with-output-recording-options (pane :record t :draw nil) ...)`

seems like a solution. I guess this delays actual output until coordinate swizzling has been set up. Is it the best approach?

**Comment by dkochmanski** [comment]
yes, that's the best way to do it right now. I've created a proposal ticket which addresses the core of the issue.
