### ISSUE TITLE
Problem with clouseau from listener in :clx port

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#888]
With the ugly port 
`(setf clim:*default-server-path* :clx)`
if I start `clouseau` like `(clouseau:inspect 1)` from the clim-listener it freeze. No error it is reported. If I start `clouseau` from `slime` all is ok. Also if I start `clouseau` from the clim-listener but in a new process all is ok: `(clouseau:inspect 1 :new-process t)`.

This  problem is present only with the ugly port with the default port `:clx-ttf` it is not present

**Comment by scymtym** [comment]
I believe I reproduced this issue. In my case, it happens when clouseau attempts to output the `→` character using the font `#<XLIB:FONT -adobe-helvetica-medium-r-normal--12-120-75-75-p-67-iso8859-1 :1 79691874>`. The (simplified) call stack looks like this:

```
1: (XLIB::BUFFER-INPUT-WAIT-DEFAULT)
2: (XLIB:DISPLAY-FINISH-OUTPUT)
3: (FORMAT LISTENER-INTERACTOR-PANE <WARNING "Character ~S not representable in font ~S">)
4: (WARN "Character ~S not representable in font ~S")
5: (CLIM-CLX::TRANSLATE "→")
6: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK CLX Buffer Lock)
7: (XLIB:DRAW-GLYPHS "→")
```

So

1. the listener thread is holding the "CLX Buffer Lock"
2. the Xlib font cannot represent the character
3. `clim-clx::translate` signals a warning because of this
4. the warning is printed, presumably with `*error-output*` bound to the listener's interactor pane
5. printing the warning causes `xlib:display-finish-output` which attempts a roundtrip
6. for the roundtrip, it ends up calling `xlib::buffer-input-wait-default`
7. i think this does not finish because the port thread is waiting for the "CLX Buffer Lock"

Deadlock.
