### ISSUE TITLE
draggable graph demo does not allow for dragging graph elements

### ISSUE THREAD

**Issue by sirherrbatka** [McCLIM/McCLIM#974]
Draggable-graph appears to be out of sync with the changes in the McCLIM. I assume this from the fact that :erase-final argument in the 106 line of the file is unexpected. Also, after removing said arguments demo runs, but clicking on any graph elements results in error. Commenting out the line 274 in the pointer-tracking file (call to which is located on the stack-trace) allows demo to run and visually i fail to notice anything visually wrong. I can't figure out the reason behind the error nor how to correctly implement demo so I can't assist any further.

Test was made on the Ubuntu 18.04 LTS, with sbcl 2.0.1. McCLIM is the newest version available in the quicklisp at the time (27.02.2020).

**Comment by scymtym** [comment]
Something seems to be wrong because line 106 of `draggable-graph.lisp` does not contain `:erase-final`. In fact, the whole file doesn't.

I haven't tried with the Quicklisp version you mention, but since the last relevant change to `draggable-graph.lisp` was well before 2020-02-27, i suspect that you are somehow looking at an old version of the file. The change that removed `:erase-final` has been made around a year ago.

**Comment by sirherrbatka** [comment]
Indeed! I can't seem to find anything like that on my home computer. How silly. Sorry for making noise.
